### REGISTER
POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "email": "test@test.de",
  "password": "12345678",
  "name": "Test User"
}

### LOGIN
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "test@test.de",
  "password": "12345678"
}